### PR TITLE
Changed the decompression library from gzip-js to pako

### PR DESCRIPTION
**Pull request by naguam**
## Overview

Replacement from gzip-js to pako for the gunzip decompression in the Update route.

## Description

Pako is a fast and maintained gzip compression/decompression library.

Gzip-js is not so maintained and crashes on files > 1MB because of node limits on array expansions.

Tested with files of a few KB, 1MB, 10MB and 30 MB.

This does not change the fact we set a limit in the configuration.

But with this commit if the limit is high, it does not crash anymore.

### CODE REVIEW

**Review by TheMeinerLP — APPROVED** [review]

**Review by PierreSchwang — CHANGES_REQUESTED** [review]
Please pin the dependencies to specific versions.

**Review by PierreSchwang — APPROVED** [review]
Seems to work for me

**Comment by NotMyFault** [comment]
Thanks for the PR, please rebase your branch to address the conflicts @naguam

**Comment by naguam** [comment]
Rebased my commits on top of the main branch

**Comment by naguam** [comment]
Thanks

**Pull request merged**
